esphome:
  name: tuyamierda
  friendly_name: tuyamierda

bk72xx:
  board: cbu

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: "Tuyamierda Fallback Hotspot"
    password: "xoriso1234"
    ap_timeout: 0s


captive_portal:

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Madrid"
    on_time:
      - seconds: 0
        minutes: 0
        hours: 13
        then:
          - logger.log: "PUMP CHECK! 5 seconds pumping"
          - switch.turn_on: pump_a
          - delay: 5s
          - switch.turn_off: pump_a

status_led:
  pin:
    number: P20
    inverted: false

switch:
  - platform: gpio
    pin: P16
    id: pump_a
    name: "Pump A"
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: P14
    id: pump_b
    name: "Pump B"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: P8
      mode: INPUT_PULLUP
      inverted: true
    name: "Button A"
    internal: true
    on_press:
      then:
        - switch.toggle: pump_a

  - platform: gpio
    pin:
      number: P7
      mode: INPUT_PULLUP
      inverted: true
    name: "Button B"
    internal: true
    on_press:
      then:
        - switch.toggle: pump_b

sensor:
  - platform: adc
    pin: P23
    name: "Analog Sensor Voltage"
    id: analog_sensor_voltage
    update_interval: 20s
    unit_of_measurement: "V"
    icon: "mdi:flash"
    filters:
      - calibrate_linear:
        - 1.06 -> 0.0
        - 2.83 -> 100
      - lambda: |
          if (x < 0) return 0;
          else if (x > 100) return 100;
          else return (x);
    accuracy_decimals: 0

  - platform: template
    name: "Soil Moisture"
    id: soil_moisture  # Add this line to define the ID
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    lambda: |-
      return map(id(analog_sensor_voltage).state, 55.81, 0, 0, 100);
    update_interval: 20s

interval:

  - interval: 30s

    then:

      - if:

          condition:

            and:

              - lambda: 'return id(soil_moisture).state < 35;'

              - lambda: |-

                  auto time_now = id(sntp_time).now();

                  return time_now.hour >= 9 && time_now.hour < 17;

          then:
          
            - logger.log: "Moisture below 20%, activating Pump A."

            - switch.turn_on: pump_a

            - delay: 10s

            - switch.turn_off: pump_a
